name: kp
description: KP GYM Management App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  intl: 0.19.0
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  path: ^1.8.3

  share_plus: ^7.1.0
  url_launcher: ^6.1.14
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/KP.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/KP.png"